services:
  - type: web
    name: food-advisor-backend
    env: python
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    buildCommand: ""
    plan: free
    envVars:
      - key: DATABASE_URL
        value:  ${DATABASE_URL}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
    autoDeploy: true

  - type: web
    name: food-advisor-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    rootDir: frontend
    plan: free
    envVars:
      - key: VITE_API_URL
        value: ${VITE_API_URL}
    autoDeploy: true
